CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    company INTEGER REFERENCES companies(id) NOT NULL,
    category INTEGER REFERENCES categories(id) NOT NULL,
    link VARCHAR(2083),
    price DECIMAL(10,2) NOT NULL,
    brand VARCHAR(200)
);